import { GameKeys } from "@vg-slots/games/keys";
import { GameTypes, Game } from "@vg-slots/types";

export const games: Game[] = [
  {
    url: '/game/hungry-slime',
    name: GameKeys.HungrySlime,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-006.png',
  },
  {
    url: '/game/infinity-ocean',
    name: GameKeys.InfinityOcean,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-004.png',
  },
  {
    url: '/game/last-samurai',
    name: GameKeys.LastSamurai,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-001.png',
  },
  {
    url: '/game/pubg',
    name: GameKeys.PUBG,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-002.png',
  },
  {
    url: 'http://staging.kissvip.one/tablebaccarat/play?id=1004',
    name: GameKeys.Baccarat,
    type: GameTypes.TableGames,
    imageUrl: '/lobby/slider-items/img-003.png',
    redirectWithToken: true,
  },
  {
    url: 'http://staging.kissvip.one/tableroulette/play',
    name: GameKeys.TableRoulette,
    type: GameTypes.TableGames,
    imageUrl: '/lobby/slider-items/img-005.png',
    logoUrl: '/lobby/slider-items/title-005.png',
    redirectWithToken: true,
  },
  {
    url: 'http://staging.kissvip.one/tablesicbo/play',
    name: GameKeys.TableSicbo,
    type: GameTypes.TableGames,
    imageUrl: '/lobby/slider-items/img-007.png',
    logoUrl: '/lobby/slider-items/title-007.png',
    redirectWithToken: true,
  },
  {
    url: '/game/football-fever',
    name: GameKeys.FootballFever,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-008.png',
  },
  {
    url: '/game/aztec-bonus-hunt',
    name: GameKeys.AztecBonusHunt,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-009.png',
    logoUrl: '/lobby/slider-items/title-009.png',
  },
  {
    url: 'http://staging.kissvip.one/12d',
    name: GameKeys.LivesCasino12D,
    type: GameTypes.LivesCasino,
    imageUrl: '/lobby/slider-items/img-010.png',
    logoUrl: '/lobby/slider-items/title-010.png',
    redirectWithToken: true,
  },
  {
    url: 'http://staging.kissvip.one/24d',
    name: GameKeys.LivesCasino24D,
    type: GameTypes.LivesCasino,
    imageUrl: '/lobby/slider-items/img-011.png',
    logoUrl: '/lobby/slider-items/title-011.png',
    redirectWithToken: true,
  },
  {
    url: 'http://staging.kissvip.one/48d',
    name: GameKeys.LivesCasino48D,
    type: GameTypes.LivesCasino,
    imageUrl: '/lobby/slider-items/img-012.png',
    logoUrl: '/lobby/slider-items/title-012.png',
    redirectWithToken: true,
  },
  {
    url: 'http://staging.kissvip.one/monopoly',
    name: GameKeys.LivesCasinoMonopoly,
    type: GameTypes.LivesCasino,
    imageUrl: '/lobby/slider-items/img-013.png',
    logoUrl: '/lobby/slider-items/title-013.png',
    redirectWithToken: true,
  },
  {
    url: 'http://staging.kissvip.one/suwit',
    name: GameKeys.LivesCasinoSuwit,
    type: GameTypes.LivesCasino,
    imageUrl: '/lobby/slider-items/img-014.png',
    logoUrl: '/lobby/slider-items/title-014.png',
    redirectWithToken: true,
  },
  {
    url: 'http://staging.kissvip.one/grandpix',
    name: GameKeys.LivesCasinoGrandpix,
    type: GameTypes.LivesCasino,
    imageUrl: '/lobby/slider-items/img-015.png',
    logoUrl: '/lobby/slider-items/title-015.png',
    redirectWithToken: true,
  },
  {
    url: '/game/rama-kien-blessing',
    name: GameKeys.RamaKienBlessing,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-016.png',
    logoUrl: '/lobby/slider-items/title-016.png',
  },
  {
    url: '/game/mahjong-ways',
    name: GameKeys.MahjongWays,
    type: GameTypes.Slot,
    imageUrl: '/lobby/slider-items/img-017.png',
    logoUrl: '/lobby/slider-items/title-017.png',
  },
];